### ISSUE TITLE
Tabline help

### ISSUE THREAD

**Issue by p-tupe** [beauwilliams/statusline.lua#5]
https://user-images.githubusercontent.com/9110181/115904081-00bca980-a482-11eb-851b-8ca54ebc3e90.mov

New tabs do now show on the tab line properly. Do I need additional config for this?

**Comment by beauwilliams** [comment]
I think there may have been some breaking changes in the api that this section of the plugin used to use.

Double checking, you are on 0.5 yeah?

I might need to read up on the api and make some changes. It was working last I checked. Seems to have broken with an nvim update it seems

**Comment by beauwilliams** [comment]
Thanks for pointing out this bug @EMPAT94 

I've fixed the issue now :)

**Comment by wizard-28** [comment]
I still have this issue, I am on neovim nightly.
![img](https://0x0.st/-Oe8.png)

**Comment by beauwilliams** [comment]
> I still have this issue, I am on neovim nightly.
> ![img](https://camo.githubusercontent.com/f645444ccf44627918e24189b8cc490381f07a2c53d1c4bf8b20c418f42b5364/68747470733a2f2f3078302e73742f2d4f65382e706e67)

Double checking. Have you pulled the latest version?

I have just tried on my end and could not provide the error. Let me know

**Comment by wizard-28** [comment]
@beauwilliams Yes, I have pulled the latest version but the problem is still there.

**Comment by beauwilliams** [comment]
> @beauwilliams Yes, I have pulled the latest version but the problem is still there.

i will need to install neovim nightly and test this as I believe its on 0.6 now. there might have been some breaking changes. if possible can you let me know if its an issue for you on 0.5 stable
